#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tepl
Version  : 4.4.0
Release  : 1
URL      : https://download.gnome.org/sources/tepl/4.4/tepl-4.4.0.tar.xz
Source0  : https://download.gnome.org/sources/tepl/4.4/tepl-4.4.0.tar.xz
Summary  : Text editor product line
Group    : Development/Tools
License  : LGPL-2.1
Requires: tepl-data = %{version}-%{release}
Requires: tepl-lib = %{version}-%{release}
Requires: tepl-license = %{version}-%{release}
Requires: tepl-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(amtk-5)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gtksourceview-4)
BuildRequires : pkgconfig(uchardet)
BuildRequires : valgrind

%description
Tepl - Text editor product line
===============================
This is version 4.4.0 of Tepl.

%package data
Summary: data components for the tepl package.
Group: Data

%description data
data components for the tepl package.


%package dev
Summary: dev components for the tepl package.
Group: Development
Requires: tepl-lib = %{version}-%{release}
Requires: tepl-data = %{version}-%{release}
Provides: tepl-devel = %{version}-%{release}
Requires: tepl = %{version}-%{release}

%description dev
dev components for the tepl package.


%package doc
Summary: doc components for the tepl package.
Group: Documentation

%description doc
doc components for the tepl package.


%package lib
Summary: lib components for the tepl package.
Group: Libraries
Requires: tepl-data = %{version}-%{release}
Requires: tepl-license = %{version}-%{release}

%description lib
lib components for the tepl package.


%package license
Summary: license components for the tepl package.
Group: Default

%description license
license components for the tepl package.


%package locales
Summary: locales components for the tepl package.
Group: Default

%description locales
locales components for the tepl package.


%prep
%setup -q -n tepl-4.4.0
cd %{_builddir}/tepl-4.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1585787179
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1585787179
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tepl
cp %{_builddir}/tepl-4.4.0/COPYING %{buildroot}/usr/share/package-licenses/tepl/01a6b4bf79aca9b556822601186afab86e8c4fbf
%make_install
%find_lang tepl-4

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Tepl-4.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/tepl-4/tepl/tepl-abstract-factory-vala.h
/usr/include/tepl-4/tepl/tepl-abstract-factory.h
/usr/include/tepl-4/tepl/tepl-application-window.h
/usr/include/tepl-4/tepl/tepl-application.h
/usr/include/tepl-4/tepl/tepl-buffer.h
/usr/include/tepl-4/tepl/tepl-encoding.h
/usr/include/tepl-4/tepl/tepl-enum-types.h
/usr/include/tepl-4/tepl/tepl-file-loader.h
/usr/include/tepl-4/tepl/tepl-file-metadata.h
/usr/include/tepl-4/tepl/tepl-file-saver.h
/usr/include/tepl-4/tepl/tepl-file.h
/usr/include/tepl-4/tepl/tepl-fold-region.h
/usr/include/tepl-4/tepl/tepl-gutter-renderer-folds.h
/usr/include/tepl-4/tepl/tepl-info-bar.h
/usr/include/tepl-4/tepl/tepl-init.h
/usr/include/tepl-4/tepl/tepl-iter.h
/usr/include/tepl-4/tepl/tepl-menu-shell.h
/usr/include/tepl-4/tepl/tepl-metadata-manager.h
/usr/include/tepl-4/tepl/tepl-notebook.h
/usr/include/tepl-4/tepl/tepl-tab-group.h
/usr/include/tepl-4/tepl/tepl-tab-label.h
/usr/include/tepl-4/tepl/tepl-tab.h
/usr/include/tepl-4/tepl/tepl-types.h
/usr/include/tepl-4/tepl/tepl-utils.h
/usr/include/tepl-4/tepl/tepl-view.h
/usr/include/tepl-4/tepl/tepl.h
/usr/lib64/libtepl-4.so
/usr/lib64/pkgconfig/tepl-4.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/tepl-4.0/TeplAbstractFactory.html
/usr/share/gtk-doc/html/tepl-4.0/TeplAbstractFactoryVala.html
/usr/share/gtk-doc/html/tepl-4.0/TeplApplication.html
/usr/share/gtk-doc/html/tepl-4.0/TeplApplicationWindow.html
/usr/share/gtk-doc/html/tepl-4.0/TeplBuffer.html
/usr/share/gtk-doc/html/tepl-4.0/TeplEncoding.html
/usr/share/gtk-doc/html/tepl-4.0/TeplFile.html
/usr/share/gtk-doc/html/tepl-4.0/TeplFileLoader.html
/usr/share/gtk-doc/html/tepl-4.0/TeplFileMetadata.html
/usr/share/gtk-doc/html/tepl-4.0/TeplFileSaver.html
/usr/share/gtk-doc/html/tepl-4.0/TeplFoldRegion.html
/usr/share/gtk-doc/html/tepl-4.0/TeplGutterRendererFolds.html
/usr/share/gtk-doc/html/tepl-4.0/TeplInfoBar.html
/usr/share/gtk-doc/html/tepl-4.0/TeplNotebook.html
/usr/share/gtk-doc/html/tepl-4.0/TeplTab.html
/usr/share/gtk-doc/html/tepl-4.0/TeplTabGroup.html
/usr/share/gtk-doc/html/tepl-4.0/TeplTabLabel.html
/usr/share/gtk-doc/html/tepl-4.0/TeplView.html
/usr/share/gtk-doc/html/tepl-4.0/annexes.html
/usr/share/gtk-doc/html/tepl-4.0/annotation-glossary.html
/usr/share/gtk-doc/html/tepl-4.0/api-breaks-1-to-2.html
/usr/share/gtk-doc/html/tepl-4.0/api-breaks-2-to-3-amtk.html
/usr/share/gtk-doc/html/tepl-4.0/api-breaks-2-to-3-tepl.html
/usr/share/gtk-doc/html/tepl-4.0/api-breaks-3-to-4-tepl.html
/usr/share/gtk-doc/html/tepl-4.0/api-breaks.html
/usr/share/gtk-doc/html/tepl-4.0/api-index-1-0.html
/usr/share/gtk-doc/html/tepl-4.0/api-index-2-0.html
/usr/share/gtk-doc/html/tepl-4.0/api-index-3-0.html
/usr/share/gtk-doc/html/tepl-4.0/api-index-4-0.html
/usr/share/gtk-doc/html/tepl-4.0/api-index-4-4.html
/usr/share/gtk-doc/html/tepl-4.0/api-index-full.html
/usr/share/gtk-doc/html/tepl-4.0/code-folding.html
/usr/share/gtk-doc/html/tepl-4.0/file-loading-and-saving.html
/usr/share/gtk-doc/html/tepl-4.0/framework.html
/usr/share/gtk-doc/html/tepl-4.0/general.html
/usr/share/gtk-doc/html/tepl-4.0/home.png
/usr/share/gtk-doc/html/tepl-4.0/index.html
/usr/share/gtk-doc/html/tepl-4.0/intro.html
/usr/share/gtk-doc/html/tepl-4.0/left-insensitive.png
/usr/share/gtk-doc/html/tepl-4.0/left.png
/usr/share/gtk-doc/html/tepl-4.0/menus-and-toolbars.html
/usr/share/gtk-doc/html/tepl-4.0/misc.html
/usr/share/gtk-doc/html/tepl-4.0/object-tree.html
/usr/share/gtk-doc/html/tepl-4.0/porting-guide-file-loading-and-saving.html
/usr/share/gtk-doc/html/tepl-4.0/porting-guides.html
/usr/share/gtk-doc/html/tepl-4.0/right-insensitive.png
/usr/share/gtk-doc/html/tepl-4.0/right.png
/usr/share/gtk-doc/html/tepl-4.0/style.css
/usr/share/gtk-doc/html/tepl-4.0/tepl-4.0-Tepl-Initialization-and-Finalization.html
/usr/share/gtk-doc/html/tepl-4.0/tepl-4.0-TeplIter.html
/usr/share/gtk-doc/html/tepl-4.0/tepl-4.0-TeplMenuShell.html
/usr/share/gtk-doc/html/tepl-4.0/tepl-4.0-TeplMetadataManager.html
/usr/share/gtk-doc/html/tepl-4.0/tepl-4.0-TeplUtils.html
/usr/share/gtk-doc/html/tepl-4.0/tepl-4.0.devhelp2
/usr/share/gtk-doc/html/tepl-4.0/tepl-api-reference.html
/usr/share/gtk-doc/html/tepl-4.0/up-insensitive.png
/usr/share/gtk-doc/html/tepl-4.0/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtepl-4.so.0
/usr/lib64/libtepl-4.so.0.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tepl/01a6b4bf79aca9b556822601186afab86e8c4fbf

%files locales -f tepl-4.lang
%defattr(-,root,root,-)

